name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --no-daemon
      env:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m"
    
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rutv-debug-apk
        path: app/build/outputs/apk/debug/rutv-debug-1.2.apk
        retention-days: 30
